### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by Urmurgurd** [azmatt/chasing_your_tail#1]
Was wondering if this could be adapted to identify device advertising IDs as and additional data set and another way of dealing with randomized MACs etc

**Comment by azmatt** [comment]
I've spoken with @Singe about this. The "Easiest" way to grab the true MAC address would be to trade the 100% passive nature of the tool to VERY briefly offer to serve up the network that the probing device was looking for. Depending on the device and settings, it may try to authenticate with it's true MAC address at that point and of course you could just drop that request.
