### ISSUE TITLE
installing kismet doesnt seem to work

### ISSUE THREAD

**Issue by V1C3-V3RS4** [azmatt/chasing_your_tail#9]
Im following the instructions from the prereq.pdf, and the instructions say to install kismet, getting all sorts of errors about apt-key being depreciated, and sources.list.d/kismet.list not existing... Im guessing something in the installation instructions is possibly outdated?

**Comment by Crunch3D** [comment]
Hello here is a link to which you will find help 
forgive me for my English

[Kismet](https://www.kismetwireless.net//docs/readme/packages/#release-or-git)
